#!/bin/sh

# Author : Arun S P
# This script initialises the City App and launches its Backend and Frontend modules

if [ -e database-initialised.flag ]
then
    echo "ok"
else
    echo "First time? Initialising the Database. This should take a sec..."

    echo "Extracting The Zip"
    tar xvzf mysql-8.0.31-macos12-x86_64.tar.gz
    mv mysql-8.0.31-macos12-x86_64 mysql-8.0.31

    echo "Initialising the Database"
    mkdir mysql-8.0.31/mysql-files
    mysqld --initialize --basedir=mysql-8.0.31

    echo Done!
    touch database-initialised.flag
fi

export PATH=$PATH:mysql-8.0.31/bin
export PATH=$PATH:mysql-8.0.31/support-files

mysqld --basedir=mysql-8.0.31 &